on:
  push:
    branches:
      - master

name: Push new image to ECR and force ECS redeploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
    
      - name: Build, tag, and push
        id: build
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/star_seeker_api:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/star_seeker_api:latest
        shell: bash

      - name: Force new deployment
        run: |
          aws ecs update-service --cluster star_seeker_api_cluster --service star_seeker_api_service --force-new-deployment
        shell: bash